CREATE TABLE HUMAN(ID INT,NAMES VARCHAR(20),AGE INT,CITY VARCHAR(20),HNO INT);

ALTER TABLE HUMAN ADD UNIQUE(HNO);

ALTER TABLE HUMAN ALTER COLUMN ID INT NOT NULL;

ALTER TABLE HUMAN ADD PRIMARY KEY(ID);

INSERT INTO HUMAN VALUES(20,'NIDHI',20,'AGRA',8677);

ALTER TABLE HUMAN ADD COUNTRY VARCHAR(20);

ALTER TABLE HUMAN DROP COLUMN COLUMN_NAME;

CREATE TABLE ORDERS(OID INT NOT NULL,CUSTOMER_ID INT);

ALTER TABLE ORDERS ADD FOREIGN KEY(OID) REFERENCES HUMAN(ID);